# Generated by Django 3.1.2 on 2020-10-06 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('timestamp', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('text', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('color', models.CharField(choices=[('primary', '#007bff'), ('secondary', '#6c757d'), ('success', '#28a745'), ('danger', '#dc3545'), ('warning', '#ffc107'), ('info', '#17a2b8')], max_length=30)),
                ('position', models.CharField(choices=[('aboveBar', 'aboveBar'), ('belowBar', 'belowBar'), ('inBar', 'inBar')], max_length=30)),
                ('shape', models.CharField(choices=[('Circle', 'circle'), ('arrowUp', 'arrowUp'), ('arrowDown', 'arrowDown')], max_length=30)),
            ],
        ),
    ]
