# Generated by Django 3.1.2 on 2020-10-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='color',
            field=models.CharField(choices=[('#007bff', 'primary'), ('#6c757d', 'secondary'), ('#28a745', 'success'), ('#dc3545', 'danger'), ('#ffc107', 'warning'), ('#17a2b8', 'info')], max_length=30),
        ),
        migrations.AlterField(
            model_name='event',
            name='shape',
            field=models.CharField(choices=[('circle', 'circle'), ('arrowUp', 'arrowUp'), ('arrowDown', 'arrowDown')], max_length=30),
        ),
        migrations.AlterField(
            model_name='event',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, max_length=150, null=True),
        ),
    ]
