# Generated by Django 3.1.2 on 2020-10-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0002_auto_20201010_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='timestamp',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
